name: Create binaries
on:
  push:
    tags:
      - "*"

permissions:
  contents: read

jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: "3.10"
          spec: "chess_insight/main.py"
          requirements: "requirements.txt"
          upload_exe_with_name: "chess_insight"
          options: --onefile, --name "Chess-insight-app", --windowed,--add-data "chess_insight/data/openings.json"
